package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer idAnuncio;
     private Perfil perfil;
     private Usuario usuario;
     private String nomeProprietario;
     private String rua;
     private String bairro;
     private String estado;
     private String cidade;
     private String descricao;
     private int qtdVagas;
     private double valorTotal;
     private int hits;
     private boolean status;
     private Set imagenses = new HashSet(0);
     private Set logOperacoeses = new HashSet(0);
     private Set anuncioVagas = new HashSet(0);

    public Anuncio() {
    }

	
    public Anuncio(Perfil perfil, Usuario usuario, String nomeProprietario, String rua, String bairro, String estado, String cidade, String descricao, int qtdVagas, double valorTotal, int hits, boolean status) {
        this.perfil = perfil;
        this.usuario = usuario;
        this.nomeProprietario = nomeProprietario;
        this.rua = rua;
        this.bairro = bairro;
        this.estado = estado;
        this.cidade = cidade;
        this.descricao = descricao;
        this.qtdVagas = qtdVagas;
        this.valorTotal = valorTotal;
        this.hits = hits;
        this.status = status;
    }
    public Anuncio(Perfil perfil, Usuario usuario, String nomeProprietario, String rua, String bairro, String estado, String cidade, String descricao, int qtdVagas, double valorTotal, int hits, boolean status, Set imagenses, Set logOperacoeses, Set anuncioVagas) {
       this.perfil = perfil;
       this.usuario = usuario;
       this.nomeProprietario = nomeProprietario;
       this.rua = rua;
       this.bairro = bairro;
       this.estado = estado;
       this.cidade = cidade;
       this.descricao = descricao;
       this.qtdVagas = qtdVagas;
       this.valorTotal = valorTotal;
       this.hits = hits;
       this.status = status;
       this.imagenses = imagenses;
       this.logOperacoeses = logOperacoeses;
       this.anuncioVagas = anuncioVagas;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomeProprietario() {
        return this.nomeProprietario;
    }
    
    public void setNomeProprietario(String nomeProprietario) {
        this.nomeProprietario = nomeProprietario;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public int getQtdVagas() {
        return this.qtdVagas;
    }
    
    public void setQtdVagas(int qtdVagas) {
        this.qtdVagas = qtdVagas;
    }
    public double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }
    public int getHits() {
        return this.hits;
    }
    
    public void setHits(int hits) {
        this.hits = hits;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Set getImagenses() {
        return this.imagenses;
    }
    
    public void setImagenses(Set imagenses) {
        this.imagenses = imagenses;
    }
    public Set getLogOperacoeses() {
        return this.logOperacoeses;
    }
    
    public void setLogOperacoeses(Set logOperacoeses) {
        this.logOperacoeses = logOperacoeses;
    }
    public Set getAnuncioVagas() {
        return this.anuncioVagas;
    }
    
    public void setAnuncioVagas(Set anuncioVagas) {
        this.anuncioVagas = anuncioVagas;
    }




}


