package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1



/**
 * AnuncioVaga generated by hbm2java
 */
public class AnuncioVaga  implements java.io.Serializable {


     private Integer idAnuncioVaga;
     private Anuncio anuncio;
     private Usuario usuario;
     private boolean aceite;
     private String obsAceite;

    public AnuncioVaga() {
    }

	
    public AnuncioVaga(Anuncio anuncio, Usuario usuario, boolean aceite) {
        this.anuncio = anuncio;
        this.usuario = usuario;
        this.aceite = aceite;
    }
    public AnuncioVaga(Anuncio anuncio, Usuario usuario, boolean aceite, String obsAceite) {
       this.anuncio = anuncio;
       this.usuario = usuario;
       this.aceite = aceite;
       this.obsAceite = obsAceite;
    }
   
    public Integer getIdAnuncioVaga() {
        return this.idAnuncioVaga;
    }
    
    public void setIdAnuncioVaga(Integer idAnuncioVaga) {
        this.idAnuncioVaga = idAnuncioVaga;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public boolean isAceite() {
        return this.aceite;
    }
    
    public void setAceite(boolean aceite) {
        this.aceite = aceite;
    }
    public String getObsAceite() {
        return this.obsAceite;
    }
    
    public void setObsAceite(String obsAceite) {
        this.obsAceite = obsAceite;
    }




}


