package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1

import org.primefaces.model.StreamedContent;




/**
 * Imagens generated by hbm2java
 */
public class Imagens  implements java.io.Serializable {


     private Integer idImages;
     private Anuncio anuncio;
     private byte[] imagem;
     private String descricaoImagem;
     private StreamedContent imgprocessada;

    public Imagens() {
    }

	
    public Imagens(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Imagens(Anuncio anuncio, byte[] imagem, String descricaoImagem) {
       this.anuncio = anuncio;
       this.imagem = imagem;
       this.descricaoImagem = descricaoImagem;
    }
   
    public Integer getIdImages() {
        return this.idImages;
    }
    
    public void setIdImages(Integer idImages) {
        this.idImages = idImages;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }
    public String getDescricaoImagem() {
        return this.descricaoImagem;
    }
    
    public void setDescricaoImagem(String descricaoImagem) {
        this.descricaoImagem = descricaoImagem;
    }

    public StreamedContent getImgprocessada() {
        return imgprocessada;
    }

    public void setImgprocessada(StreamedContent imgprocessada) {
        this.imgprocessada = imgprocessada;
    }




}


