package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogLogin generated by hbm2java
 */
public class LogLogin  implements java.io.Serializable {


     private Integer idlog;
     private Usuario usuario;
     private Date dataLogin;
     private Date dataLoggout;

    public LogLogin() {
    }

    public LogLogin(Usuario usuario, Date dataLogin, Date dataLoggout) {
       this.usuario = usuario;
       this.dataLogin = dataLogin;
       this.dataLoggout = dataLoggout;
    }
   
    public Integer getIdlog() {
        return this.idlog;
    }
    
    public void setIdlog(Integer idlog) {
        this.idlog = idlog;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataLogin() {
        return this.dataLogin;
    }
    
    public void setDataLogin(Date dataLogin) {
        this.dataLogin = dataLogin;
    }
    public Date getDataLoggout() {
        return this.dataLoggout;
    }
    
    public void setDataLoggout(Date dataLoggout) {
        this.dataLoggout = dataLoggout;
    }




}


