package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogOperacoes generated by hbm2java
 */
public class LogOperacoes  implements java.io.Serializable {


     private Integer idLogOperacoes;
     private Anuncio anuncio;
     private String tipoOperacao;
     private Date dataOperacao;
     private int idUsuarioOperacao;

    public LogOperacoes() {
    }

    public LogOperacoes(Anuncio anuncio, String tipoOperacao, Date dataOperacao, int idUsuarioOperacao) {
       this.anuncio = anuncio;
       this.tipoOperacao = tipoOperacao;
       this.dataOperacao = dataOperacao;
       this.idUsuarioOperacao = idUsuarioOperacao;
    }
   
    public Integer getIdLogOperacoes() {
        return this.idLogOperacoes;
    }
    
    public void setIdLogOperacoes(Integer idLogOperacoes) {
        this.idLogOperacoes = idLogOperacoes;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public String getTipoOperacao() {
        return this.tipoOperacao;
    }
    
    public void setTipoOperacao(String tipoOperacao) {
        this.tipoOperacao = tipoOperacao;
    }
    public Date getDataOperacao() {
        return this.dataOperacao;
    }
    
    public void setDataOperacao(Date dataOperacao) {
        this.dataOperacao = dataOperacao;
    }
    public int getIdUsuarioOperacao() {
        return this.idUsuarioOperacao;
    }
    
    public void setIdUsuarioOperacao(int idUsuarioOperacao) {
        this.idUsuarioOperacao = idUsuarioOperacao;
    }




}


