package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private boolean fuma;
     private boolean bebe;
     private boolean chegaMadrugada;
     private boolean solteiro;
     private boolean fazFestaCasa;
     private boolean cozinhaLimpaCasa;
     private Set anuncios = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(boolean fuma, boolean bebe, boolean chegaMadrugada, boolean solteiro, boolean fazFestaCasa, boolean cozinhaLimpaCasa) {
        this.fuma = fuma;
        this.bebe = bebe;
        this.chegaMadrugada = chegaMadrugada;
        this.solteiro = solteiro;
        this.fazFestaCasa = fazFestaCasa;
        this.cozinhaLimpaCasa = cozinhaLimpaCasa;
    }
    public Perfil(boolean fuma, boolean bebe, boolean chegaMadrugada, boolean solteiro, boolean fazFestaCasa, boolean cozinhaLimpaCasa, Set anuncios, Set usuarios) {
       this.fuma = fuma;
       this.bebe = bebe;
       this.chegaMadrugada = chegaMadrugada;
       this.solteiro = solteiro;
       this.fazFestaCasa = fazFestaCasa;
       this.cozinhaLimpaCasa = cozinhaLimpaCasa;
       this.anuncios = anuncios;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public boolean isFuma() {
        return this.fuma;
    }
    
    public void setFuma(boolean fuma) {
        this.fuma = fuma;
    }
    public boolean isBebe() {
        return this.bebe;
    }
    
    public void setBebe(boolean bebe) {
        this.bebe = bebe;
    }
    public boolean isChegaMadrugada() {
        return this.chegaMadrugada;
    }
    
    public void setChegaMadrugada(boolean chegaMadrugada) {
        this.chegaMadrugada = chegaMadrugada;
    }
    public boolean isSolteiro() {
        return this.solteiro;
    }
    
    public void setSolteiro(boolean solteiro) {
        this.solteiro = solteiro;
    }
    public boolean isFazFestaCasa() {
        return this.fazFestaCasa;
    }
    
    public void setFazFestaCasa(boolean fazFestaCasa) {
        this.fazFestaCasa = fazFestaCasa;
    }
    public boolean isCozinhaLimpaCasa() {
        return this.cozinhaLimpaCasa;
    }
    
    public void setCozinhaLimpaCasa(boolean cozinhaLimpaCasa) {
        this.cozinhaLimpaCasa = cozinhaLimpaCasa;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


