package entity;
// Generated 01/11/2017 18:21:14 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Perfil perfil;
     private String nome;
     private String email;
     private String senha;
     private byte[] foto;
     private String rg;
     private String cpf;
     private String sexo;
     private Date dataNascimento;
     private String telefone;
     private String celular;
     private boolean permissao;
     private Set anuncioVagas = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set logLogins = new HashSet(0);
     private Set anuncios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Perfil perfil, String nome, String email, String senha, String cpf, String sexo, Date dataNascimento, String celular, boolean permissao) {
        this.perfil = perfil;
        this.nome = nome;
        this.email = email;
        this.senha = senha;
        this.cpf = cpf;
        this.sexo = sexo;
        this.dataNascimento = dataNascimento;
        this.celular = celular;
        this.permissao = permissao;
    }
    public Usuario(Perfil perfil, String nome, String email, String senha, byte[] foto, String rg, String cpf, String sexo, Date dataNascimento, String telefone, String celular, boolean permissao, Set anuncioVagas, Set contratos, Set logLogins, Set anuncios) {
       this.perfil = perfil;
       this.nome = nome;
       this.email = email;
       this.senha = senha;
       this.foto = foto;
       this.rg = rg;
       this.cpf = cpf;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.telefone = telefone;
       this.celular = celular;
       this.permissao = permissao;
       this.anuncioVagas = anuncioVagas;
       this.contratos = contratos;
       this.logLogins = logLogins;
       this.anuncios = anuncios;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public boolean isPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(boolean permissao) {
        this.permissao = permissao;
    }
    public Set getAnuncioVagas() {
        return this.anuncioVagas;
    }
    
    public void setAnuncioVagas(Set anuncioVagas) {
        this.anuncioVagas = anuncioVagas;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getLogLogins() {
        return this.logLogins;
    }
    
    public void setLogLogins(Set logLogins) {
        this.logLogins = logLogins;
    }
    public Set getAnuncios() {
        return this.anuncios;
    }
    
    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }




}


